global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'video-rss-monitor'
    environment: 'production'

rule_files:
  - "alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # DCGM Exporter - GPU metrics
  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    scrape_interval: 10s
    metrics_path: /metrics

  # Video processing components
  - job_name: 'video-metadata-extractor'
    static_configs:
      - targets: ['video-metadata-extractor:8001']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'audio-processor'
    static_configs:
      - targets: ['audio-processor:8002']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'transcription-engine'
    static_configs:
      - targets: ['transcription-engine:8003']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'video-content-analyzer'
    static_configs:
      - targets: ['video-content-analyzer:8004']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'summarization-engine'
    static_configs:
      - targets: ['summarization-engine:8005']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'rss-server'
    static_configs:
      - targets: ['rss-server:8006']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'distributed-cache'
    static_configs:
      - targets: ['cache-manager:8007']
    scrape_interval: 15s
    metrics_path: /metrics

  # Model serving infrastructure
  - job_name: 'triton-inference-server'
    static_configs:
      - targets: ['triton-inference-service:8002']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'model-optimizer'
    static_configs:
      - targets: ['model-optimizer-service:8003']
    scrape_interval: 15s
    metrics_path: /metrics

  # Real-time streaming components
  - job_name: 'webrtc-server'
    static_configs:
      - targets: ['webrtc-server:8090']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'event-pipeline'
    static_configs:
      - targets: ['event-pipeline:8091']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'backpressure-controller'
    static_configs:
      - targets: ['backpressure-controller:8095']
    scrape_interval: 10s
    metrics_path: /metrics

  # Kafka metrics
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # Custom video processing metrics
  - job_name: 'video-metrics-exporter'
    static_configs:
      - targets: ['video-metrics-exporter:9500']
    scrape_interval: 15s
    metrics_path: /metrics

  # Elasticsearch metrics
  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s
    metrics_path: /metrics

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://rss-server:8006/health
        - http://webrtc-server:8090/health
        - http://triton-inference-service:8000/v2/health/ready
        - http://video-metadata-extractor:8001/health
        - http://audio-processor:8002/health
        - http://transcription-engine:8003/health
        - http://video-content-analyzer:8004/health
        - http://summarization-engine:8005/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # JMX metrics for Java components (Flink)
  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['flink-jobmanager:8081']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['flink-taskmanager-1:8081', 'flink-taskmanager-2:8081']
    scrape_interval: 15s
    metrics_path: /metrics

# Service discovery for dynamic targets
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - model-serving
            - video-processing
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

# Recording rules for aggregations
recording_rules:
  - name: video_processing.rules
    interval: 30s
    rules:
      - record: video_processing:throughput_per_second
        expr: rate(video_events_processed_total[1m])

      - record: video_processing:error_rate
        expr: rate(video_events_failed_total[1m]) / rate(video_events_total[1m])

      - record: video_processing:latency_p99
        expr: histogram_quantile(0.99, rate(video_processing_duration_seconds_bucket[5m]))

      - record: video_processing:queue_utilization
        expr: video_processing_queue_size / video_processing_queue_capacity

# Remote storage (optional - for long-term storage)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "user"
#       password: "pass"

# Remote read (optional - for federated queries)
# remote_read:
#   - url: "https://your-remote-storage/api/v1/read"