apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
      cacheLevel: 'High'
      incrementalQueryOverlapWindow: 10m

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [
          {
            key: 'service.name',
            value: 'service'
          }
        ]
        mapTagNamesEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: '[logs-]YYYY.MM.DD'
    editable: true
    jsonData:
      interval: Daily
      timeField: '@timestamp'
      esVersion: '8.9.0'
      maxConcurrentShardRequests: 5
      logMessageField: 'message'
      logLevelField: 'level'

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: 'jaeger'
          matcherRegex: 'traceID=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: video_rss_metrics
    user: admin
    secureJsonData:
      password: admin123
    editable: true
    jsonData:
      version: InfluxQL
      timeInterval: 10s
      httpMode: GET

  - name: CloudWatch
    type: cloudwatch
    editable: true
    jsonData:
      authType: keys
      defaultRegion: us-east-1
    secureJsonData:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

  - name: TestData
    type: testdata
    editable: true

# Template variables for dynamic dashboards
templating:
  list:
    - name: environment
      type: constant
      current:
        value: production
      options:
        - production
        - staging
        - development

    - name: datasource
      type: datasource
      query: prometheus
      current:
        value: Prometheus

    - name: instance
      type: query
      datasource: Prometheus
      query: 'label_values(up, instance)'
      regex: ''
      sort: 1
      refresh: 2
      includeAll: true
      allValue: '.*'

    - name: job
      type: query
      datasource: Prometheus
      query: 'label_values(up, job)'
      regex: ''
      sort: 1
      refresh: 2
      includeAll: true
      allValue: '.*'

    - name: gpu
      type: query
      datasource: Prometheus
      query: 'label_values(DCGM_FI_DEV_GPU_UTIL, gpu)'
      regex: ''
      sort: 3
      refresh: 2
      includeAll: true
      allValue: '.*'