apiVersion: v1
kind: Namespace
metadata:
  name: model-serving
  labels:
    name: model-serving
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: model-serving-quota
  namespace: model-serving
spec:
  hard:
    requests.nvidia.com/gpu: "8"
    requests.cpu: "64"
    requests.memory: "256Gi"
    persistentvolumeclaims: "10"
    services: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: model-serving-limits
  namespace: model-serving
spec:
  limits:
  - max:
      nvidia.com/gpu: "4"
      cpu: "16"
      memory: "64Gi"
    min:
      cpu: "1"
      memory: "2Gi"
    default:
      cpu: "4"
      memory: "16Gi"
    defaultRequest:
      cpu: "2"
      memory: "8Gi"
    type: Container