version: '3.8'

services:
  # Redis Cluster Configuration
  redis-master-1:
    image: redis:7-alpine
    container_name: redis-master-1
    ports:
      - "7000:7000"
    volumes:
      - ./data/redis-1:/data
      - ./config/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-enabled yes --cluster-config-file nodes-7000.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - cache-network

  redis-master-2:
    image: redis:7-alpine
    container_name: redis-master-2
    ports:
      - "7001:7001"
    volumes:
      - ./data/redis-2:/data
      - ./config/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7001 --cluster-enabled yes --cluster-config-file nodes-7001.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - cache-network

  redis-master-3:
    image: redis:7-alpine
    container_name: redis-master-3
    ports:
      - "7002:7002"
    volumes:
      - ./data/redis-3:/data
      - ./config/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7002 --cluster-enabled yes --cluster-config-file nodes-7002.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - cache-network

  redis-replica-1:
    image: redis:7-alpine
    container_name: redis-replica-1
    ports:
      - "7003:7003"
    volumes:
      - ./data/redis-4:/data
      - ./config/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7003 --cluster-enabled yes --cluster-config-file nodes-7003.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - cache-network

  redis-replica-2:
    image: redis:7-alpine
    container_name: redis-replica-2
    ports:
      - "7004:7004"
    volumes:
      - ./data/redis-5:/data
      - ./config/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7004 --cluster-enabled yes --cluster-config-file nodes-7004.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - cache-network

  redis-replica-3:
    image: redis:7-alpine
    container_name: redis-replica-3
    ports:
      - "7005:7005"
    volumes:
      - ./data/redis-6:/data
      - ./config/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7005 --cluster-enabled yes --cluster-config-file nodes-7005.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - cache-network

  # Redis Sentinel for High Availability
  redis-sentinel-1:
    image: redis:7-alpine
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      - cache-network

  redis-sentinel-2:
    image: redis:7-alpine
    container_name: redis-sentinel-2
    ports:
      - "26380:26380"
    volumes:
      - ./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26380
    networks:
      - cache-network

  redis-sentinel-3:
    image: redis:7-alpine
    container_name: redis-sentinel-3
    ports:
      - "26381:26381"
    volumes:
      - ./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26381
    networks:
      - cache-network

  # Apache Cassandra Cluster
  cassandra-1:
    image: cassandra:4.1
    container_name: cassandra-1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=VideoRSSCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    volumes:
      - ./data/cassandra-1:/var/lib/cassandra
      - ./config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - cache-network

  cassandra-2:
    image: cassandra:4.1
    container_name: cassandra-2
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=VideoRSSCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack2
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    volumes:
      - ./data/cassandra-2:/var/lib/cassandra
      - ./config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    depends_on:
      - cassandra-1
    networks:
      - cache-network

  cassandra-3:
    image: cassandra:4.1
    container_name: cassandra-3
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=VideoRSSCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack3
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    volumes:
      - ./data/cassandra-3:/var/lib/cassandra
      - ./config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    depends_on:
      - cassandra-2
    networks:
      - cache-network

  # Cache Manager Service
  cache-manager:
    build: ./cache-manager
    container_name: cache-manager
    ports:
      - "8090:8090"
    environment:
      - REDIS_CLUSTER_NODES=redis-master-1:7000,redis-master-2:7001,redis-master-3:7002
      - CASSANDRA_NODES=cassandra-1:9042,cassandra-2:9042,cassandra-3:9042
      - LOG_LEVEL=info
    depends_on:
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - cassandra-1
    networks:
      - cache-network

  # Monitoring
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis-master-1:7000,redis-master-2:7001,redis-master-3:7002
    networks:
      - cache-network

  cassandra-exporter:
    image: criteord/cassandra_exporter:latest
    container_name: cassandra-exporter
    ports:
      - "9500:9500"
    environment:
      - CASSANDRA_HOST=cassandra-1
    networks:
      - cache-network

networks:
  cache-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16